#!/bin/sh
set -e

install -d -m755 -o root -g root /etc/openvpn-desk
install -d -m700 -o root -g root /etc/openvpn-desk/profiles

systemctl daemon-reload || true

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f /usr/share/icons/hicolor || true
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications || true
fi
